apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: francesshen/docker-fastapi:976a69482241ff79f676561074dd5a8861618045
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
