apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: francesshen/docker-fastapi:d13c14c231ac9ebb298746ea68418bca397d8852
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
