apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: francesshen/docker-fastapi:6eea2118b0ff1fa0de5bb5b066836319ac3e8a95
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
